services:
  kerberos:
    domain: CORP.EXAMPLE.COM
    enabled: true
    image: mycorp.jfrog.io/docker-mirror/mycorp-approved-images/kerberos-base:latest
    use_prebuilt: true
  postgres:
    auth_method: trust
    enabled: true
    image: fake.registry.corp.com/postgres/special:99.99
    password: null
    prebuilt: false
