version: "1.0"
platform_name: "test-clean-slate"
services:
  postgres:
    enabled: true
    image: "mycorp.jfrog.io/docker-mirror/mycorp-approved-images/postgres/17.5:2025.10.01"
  kerberos:
    enabled: true
    image: "mycorp.jfrog.io/docker-mirror/mycorp-approved-images/kerberos-base:latest"
    mode: "prebuilt"
  openmetadata:
    enabled: true
    server_image: "artifactory.corp.net/docker-public/openmetadata/server:1.5.11-approved"
