# Lightweight PostgreSQL sandbox for datakit testing
# Ephemeral - designed to be started/stopped frequently for testing

services:
  test-postgres:
    image: bitnami/postgresql:17.2.0  # Standardized with our infrastructure
    container_name: datakit-test-db
    restart: "no"  # Don't auto-restart - this is for testing only

    environment:
      # Bitnami PostgreSQL environment variables
      POSTGRESQL_USERNAME: test_user
      POSTGRESQL_DATABASE: datakit_tests
      # Allow empty passwords for local development testing
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_ENABLE_LDAP: "no"
      POSTGRESQL_ENABLE_TLS: "no"

      # Optimized for testing (faster startup, less durability)
      POSTGRESQL_FSYNC: "off"
      POSTGRESQL_SYNCHRONOUS_COMMIT: "off"
      POSTGRESQL_WAL_BUFFERS: "1MB"
      POSTGRESQL_CHECKPOINT_SEGMENTS: "8"

      # Security: Run as non-root
      BITNAMI_DEBUG: false

    ports:
      - "15444:5432"  # Test-specific port to avoid conflicts

    # No persistent volume - ephemeral testing
    # Data is lost when container stops (intentional for clean tests)

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d datakit_tests"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

    # Resource limits for testing (lightweight)
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
