# Simple Local Docker Registry
# ============================
# Standalone registry for local development (no Traefik, no proxy, no AGPL UI)
# Registry image is Apache 2.0 licensed and enterprise-friendly
#
# Image sources configured via .env:
# - ARTIFACTORY_REGISTRY_IMAGE (corporate) or registry:2 (public default)

services:
  # Simple local registry
  registry:
    image: ${ARTIFACTORY_REGISTRY_IMAGE:-registry:2}
    container_name: registry
    restart: unless-stopped
    ports:
      - "${REGISTRY_CACHE_PORT:-5000}:5000"
    volumes:
      - registry_data:/var/lib/registry
    environment:
      # Basic configuration
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
    networks:
      - registry-net

volumes:
  registry_data:

networks:
  registry-net:
    driver: bridge
