apiVersion: v1
kind: Pod
metadata:
  name: worker-dbt
spec:
  containers:
  - name: worker-dbt
    image: registry.localhost/platform/airflow-base:3.0-10
    resources:
      requests: { cpu: "2000m", memory: "4Gi" }
      limits:   { cpu: "4", memory: "8Gi" }
