version: "3.8"

networks:
  edge:
    external: true  # created by traefik-bundle
  default:
    name: airflow-obsv-net

volumes:
  krb_ccache:
  dbt_profiles:

services:
  webserver:
    networks:
      - default
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airflow-obsv.rule=Host(`${SUBDOMAIN_STANDARD}`)"
      - "traefik.http.routers.airflow-obsv.entrypoints=websecure"
      - "traefik.http.routers.airflow-obsv.tls=true"
      - "traefik.http.services.airflow-obsv.loadbalancer.server.port=8080"

  scheduler:
    volumes:
      - krb_ccache:/krb5cc:rw

  # Kerberos sidecar (Option B): obtains tickets into shared volume
  krb-sidecar:
    image: alpine:3.20
    command: >
      sh -c "
        apk add --no-cache krb5 krb5-libs krb5-conf &&
        mkdir -p /krb5 &&
        # Expect keytab mounted at /krb5/dev.keytab (provide in local env)
        while true; do
          echo 'Refreshing TGT...' &&
          kinit -kt $KRB_KEYTAB_PATH $KRB_PRINCIPAL &&
          cp /tmp/krb5cc_0 /krb5cc/krb5cc &&
          sleep 3600;
        done
      "
    environment:
      - KRB_PRINCIPAL=${KRB_PRINCIPAL}
      - KRB_KEYTAB_PATH=${KRB_KEYTAB_PATH}
    volumes:
      - krb_ccache:/krb5cc:rw
      - ./include:/krb5:ro
    networks:
      - default

  # Optional: dbt profiles in a shared volume if you prefer mounting once
  dbt-profiles:
    image: busybox
    command: ["sh","-c","tail -f /dev/null"]
    volumes:
      - dbt_profiles:/app/profiles
    networks:
      - default
