pagila:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      dbname: pagila_wh
      schema: pagila_silver
      port: 5432
      threads: 4
