version: 2
models:
  - name: dim_film
    columns:
      - name: film_id
        tests: [not_null, unique]
  - name: dim_store
    columns:
      - name: store_id
        tests: [not_null, unique]
  - name: dim_staff
    columns:
      - name: staff_id
        tests: [not_null, unique]
  - name: dim_date
    columns:
      - name: date_key
        tests: [not_null, unique]
